steps:
# Passo 1: Construir a imagem Docker usando o Dockerfile do seu projeto.
- name: 'gcr.io/cloud-builders/docker'
  args:
    # 'build' é o comando do docker.
    # '-t' é a tag ou nome que daremos à imagem.
    # O formato é: [região]-docker.pkg.dev/[ID_DO_PROJETO]/[NOME_DO_REPOSITÓRIO]/[NOME_DA_IMAGEM]:[VERSÃO]
    - 'build'
    - '-t'
    - 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/dashboard-repo/dashboard-sipat:latest'
    # '.' significa que o Dockerfile está no diretório atual.
    - '.'

# Passo 2: Enviar (push) a imagem construída para o Artifact Registry.
- name: 'gcr.io/cloud-builders/docker'
  args:
    # 'push' é o comando do docker.
    - 'push'
    - 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/dashboard-repo/dashboard-sipat:latest'

# Define a imagem construída como o resultado final que pode ser usado por outros serviços.
images:
- 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/dashboard-repo/dashboard-sipat:latest'