# 1. Imagem Base
# versão 3.11,
FROM python:3.11-slim

# 2. Diretório de Trabalho.
WORKDIR /app

# 3. Instalação de Dependências.
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copiar a Aplicação.
COPY . .

# 5. Expor a Porta.
EXPOSE 8050

# 6. Comando de Execução.
CMD ["gunicorn", "--bind", "0.0.0.0:8050", "--timeout", "120", "src.run_secure_app:server"]